### ISSUE TITLE
Project page showing multiple species not belonging to the project constraints

### ISSUE THREAD

**Issue by harshithjv** [biodiv-platform/biodiv-ui#175]
This is sheildtail mapping project:
https://indiabiodiversity.org/group/Shieldtail_Mapping_Project

Shows species count as `40`:
![image](https://user-images.githubusercontent.com/809278/142355671-842fa8a5-22f0-4769-8873-96e64cac3ec1.png)

After loading species page by clicking on the 'species' card, there are mix of different species along with shieldtails:

![image](https://user-images.githubusercontent.com/809278/142355870-6c8569d7-1b9f-48ba-9dcc-0d62c39c7e2c.png)

![image](https://user-images.githubusercontent.com/809278/142355926-256f3c85-ae28-4f6e-b1a4-d91ffbddc806.png)

Can keep on scrolling to infinitely load multiple unrelated species. It should be ideally restricted to only shieldtail species and species card be `40` or whatever future taxonomy dictates.

**Comment by harshzalavadiya** [comment]
@harshithjv thank you for creating this issue
currently we are working on new species list page that will have filters applied in group context, it will be few days before we launch it but I'll be sure to notify it here when it does

**Comment by harshithjv** [comment]
@ harshzalavadiya  cool. 😄

**Comment by teamdraftbox** [comment]
@harshithjv we have added the species list feature with filter options and group context . Please check it out
https://indiabiodiversity.org/group/Indian_Snakes/species/list?groupName=Indian_Snakes&max=16&offset=0&sort=species.dateCreated&userGroupList=24&view=grid
